use studentski_centar;
insert into fakultet values(301, 'Dekan Ekonomskog fakulteta', 'https://www.ekof.bg.ac.rs/', 'dekanat@ekof.bg.ac.rs');
insert into fakultet values(302, 'Dekan Pravnog fakulteta', 'http://www.ius.bg.ac.rs/', 'pravni@ius.bg.ac.rs');
insert into fakultet values(303, 'Dekan Pravoslavnog bogoslovskog fakulteta', 'https://www.bfspc.bg.ac.rs/?reload', 'dekan@bfspc.bg.ac.rs');
insert into fakultet values(304, 'Dekan Učiteljskog fakulteta', 'http://www.uf.bg.ac.rs/', 'dekanat@uf.bg.ac.rs');
insert into fakultet values(305, 'Dekan Fakulteta bezbednosti', 'http://fb.bg.ac.rs/', 'dekanat@fb.bg.ac.rs');
insert into fakultet values(306, 'Dekan FASPER', 'http://www.fasper.bg.ac.rs/', 'info@fasper.bg.ac.rs');
insert into fakultet values(307, 'Dekan Fakulteta političkih nauka', 'http://www.fpn.bg.ac.rs/', 'fpn@fpn.bg.ac.rs');
insert into fakultet values(308, 'Dekan FSFV', 'http://www.fsfv.bg.ac.rs/', 'http://www.fsfv.bg.ac.rs/');
insert into fakultet values(309, 'Dekan Filozofskog fakulteta', 'http://www.f.bg.ac.rs/', 'info@f.bg.ac.rs');
insert into fakultet values(310, 'Dekan Filološkog fakulteta', 'http://www.fil.bg.ac.rs/', 'info@fil.bg.ac.rs');
insert into fakultet values(311, 'Dekan Biološkog fakulteta', 'https://www.bio.bg.ac.rs/', 'dekanat@bio.bg.ac.rs');
insert into fakultet values(312, 'Dekan Geografskog fakulteta', 'http://www.gef.bg.ac.rs/', 'dekanat@gef.bg.ac.rs');
insert into fakultet values(313, 'Dekan Matematičkog fakulteta', 'http://www.matf.bg.ac.rs/', 'matf@matf.bg.ac.rs');
insert into fakultet values(314, 'Dekan Fakulteta za fizičku hemiju', 'matf@matf.bg.ac.rs', 'ffh@ffh.bg.ac.rs');
insert into fakultet values(315, 'Dekan Fizičkog fakulteta', 'http://www.ff.bg.ac.rs', 'dekanat@ff.bg.ac.rs');
insert into fakultet values(316, 'Dekan Hemijskog fakulteta', 'http://www.chem.bg.ac.rs/', 'dekan@chem.bg.ac.rs"');
insert into fakultet values(317, 'Dekan Medicinskog fakulteta', 'http://www.mfub.bg.ac.rs/', 'mf.bg@med.bg.ac.rs');
insert into fakultet values(318, 'Dekan Stomatološkog fakulteta', 'http://www.stomf.bg.ac.rs/code/navigate.php?Id=1', 'stomfak@rcub.bg.ac.rs');
insert into fakultet values(319, 'Dekan Veterinarskog fakulteta', 'http://www.vet.bg.ac.rs/', 'dekanat@vet.bg.ac.rs');
insert into fakultet values(320, 'Dekan Farmaceutskog fakulteta', 'http://www.pharmacy.bg.ac.rs/', 'info@pharmacy.bg.ac.rs');
insert into fakultet values(321, 'Dekan Arhitektonskog fakulteta', 'http://www.arh.bg.ac.rs/', 'fakultet@arh.bg.ac.rs');
insert into fakultet values(322, 'Dekan Građevinskog fakulteta', 'https://www.grf.bg.ac.rs/home', 'dekanat@grf.bg.ac.rs');
insert into fakultet values(323, 'Dekan Elektrotehničkog fakulteta', 'https://www.etf.bg.ac.rs/', 'dekanat@etf.bg.ac.rs');
insert into fakultet values(324, 'Dekan Mašinskog fakulteta', 'https://www.mas.bg.ac.rs/', 'dekan@mas.bg.ac.rs');
insert into fakultet values(325, 'Dekan Poljoprivrednog fakulteta', 'http://www.agrif.bg.ac.rs/', 'office@agrif.bg.ac.rs');
insert into fakultet values(326, 'Dekan Rudarsko-geološkog fakulteta', 'http://www.rgf.bg.ac.rs/', 'dekan@rgf.bg.ac.rs');
insert into fakultet values(327, 'Dekan Saobraćajnog fakulteta', 'http://www.sf.bg.ac.rs/index.php/sr-rs/', 'dean@sf.bg.ac.rs');
insert into fakultet values(328, 'Dekan Tehničkog fakulteta', 'https://www.tfbor.bg.ac.rs/index_cir.php', 'office@tfbor.bg.ac.rs');
insert into fakultet values(329, 'Dekan Tehnološk-metalurškog fakulteta', 'http://www.tmf.bg.ac.rs/', 'tmf@tmf.bg.ac.rs');
insert into fakultet values(330, 'Dekan FON-a', 'http://www.fon.bg.ac.rs/', 'dekanat@fon.bg.ac.rs');
insert into fakultet values(331, 'Dekan Šumarskog fakulteta', 'http://www.sfb.bg.ac.rs/', 'office@sfb.bg.ac.rs');
